### ISSUE TITLE
Configurable footer and sidebars

### ISSUE THREAD

**Issue by vgoel** [chrisrhymes/bulma-clean-theme#1]
Hey!
Great theme, just came across it and it seems super powerful. I would like to see if its possible to create a configurable footer based on the nav structure you have defined. 
As an example, in menu.yml within _data:

items:
- name: Page With Sidebar
   link: /page-1/
   nav_footer: yes
- name: Page Without Sidebar
   link: /page-2/
   nav_footer: no

However, it would be nice to have flexbox configurable as well to include the nav links in a given box. But maybe that is asking too much....

Same for sidebars if possible (currently only latest blog posts are there)

I may be able to help add this but I would need to work with you to come up with a proper structure.  

Reasoning: Would like to use this theme for a baseline for online marketing/ecommerce type sites. Would love to have integration with formspree or something similar for getting email signups etc , in the footer and possibly in a sidebar as well (configurable).

Any ideas?

**Comment by chrisrhymes** [comment]
Hi @vgoel, thanks for the feedback! 

I like the idea of footer links so I have now added these to the theme. Please see the [readme](https://github.com/chrisrhymes/bulma-clean-theme#footer) for instructions on setting them up. 

I've kept it separate from the other menu yaml file as you might have links in the footer that are not in the main navigation or side menu bar, such as cookies and privacy policies, etc. 

I'll have a think about the other changes, but in the mean time, if you want to further customise the theme you could try [overriding the theme default](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) files as per the Jekyll documentation.

**Comment by vgoel** [comment]
Thanks for the fast turnaround! Looks really good!
I will close this issue for now. I am going to see if I can do further enhancements and submit a PR if they are worthy of being included.  Thanks again!

**Comment by chrisrhymes** [comment]
@vgoel just to let you know I have just implemented simple [product pages](https://github.com/chrisrhymes/bulma-clean-theme#products) in the theme as well. 

[Product page demo](http://www.csrhymes.com/bulma-clean-theme/products/)

Hope you find them useful.

**Comment by vgoel** [comment]
That is bloody brilliant!  Thanks a ton. This is a super useful feature.
I will play with it and report back

**Comment by GreatGodApollo** [comment]
I understand this issue is closed, but would it be possible for an option to disable the footer on pages?

**Comment by chrisrhymes** [comment]
Hi @greatgodapollo you can create an _includes directory in your site and create an empty file called footer.html to overwrite the default footer. See [overwriting theme defaults](https://jekyllrb.com/docs/themes/) for more info.

**Comment by GreatGodApollo** [comment]
It's not that I don't want a footer, it's that I'd like to be able to disable the footer on certain pages.

**Comment by chrisrhymes** [comment]
@GreatGodApollo you can now [disable the footer on a page by page basis](https://github.com/chrisrhymes/bulma-clean-theme#hiding-the-footer)

#7
