### ISSUE TITLE
Dropdown feature not working in IE browsers

### ISSUE THREAD

**Issue by markbarratt** [chrisrhymes/bulma-clean-theme#10]
The dropdown feature doesn't work on Edge or IE11.

**Comment by chrisrhymes** [comment]
It looks like this issue has been reported with [Bulma 0.7.5](https://github.com/jgthms/bulma/issues/2503). I have duplicated some css in the theme to resolve this issue with the theme until Bulma is updated. 

#12 

Please can you test with the latest version of master or gem v0.5.5 and see if this resolves your issue?

**Comment by markbarratt** [comment]
Thanks. This issue is resolved with the current master.
