### ISSUE TITLE
Navbar occludes headings if fixed

### ISSUE THREAD

**Issue by mzenk** [chrisrhymes/bulma-clean-theme#103]
Thank you for this nice theme! For me as a beginner it was the perfect way to start building my project website and learn about a few customizations along the way. One small issue I encountered was the following: When using `fixed_navbar: top` in the config, the navigation bar at the top occludes headings when following a link to the heading. Is it possible to fix this in the theme?
I attached an example page to reproduce the error.
[test.md](https://github.com/chrisrhymes/bulma-clean-theme/files/6521201/test.md)

**Comment by chrisrhymes** [comment]
Hi, thanks for your feedback. The issue with the fixed header is standard browser behaviour. If you want to resolve this you could either add some custom css to add margin above the heading or add some JavaScript to adjust the scroll position. You can create a `_includes/head-scripts.html` file and put custom JavaScript in there without the need to overwrite the default head.html.
