### ISSUE TITLE
Per-page themes (or CSS)

### ISSUE THREAD

**Issue by Pennycook** [chrisrhymes/bulma-clean-theme#106]
We're using this theme for a series of workshops that we run, where each individual event is set up in a separate folder (organized by year) and part of the same Jekyll site.  Having the ability to provide custom colors for the different years would be really useful for us, and I imagine also for others looking to have multiple sub-sites.

I can hack something together locally using a custom layout and the instructions [from here](https://jreel.github.io/per-page-custom-css-in-jekyll/) to enable per-page custom CSS, but it would be much more convenient if this capability was part of the theme itself.  As is, it looks like we'll have to create local copies of all the bulma-clean-theme layouts we want to modify, and keep them in sync.

Apologies if there's a more obvious way to do this.  I'm very new to Jekyll!

**EDIT**: I managed to get this working eventually by overriding `head.html` in the `_includes` folder, as shown [here](https://github.com/P3HPC/p3hpc.github.io/blob/90bc3833433f56824fbdd138b8a0efd034ae3314/_includes/head.html).  I'm happy with this as a solution -- so feel free to close this issue -- but I do still think it would be nice if the theme could incorporate something like this.

**Comment by chrisrhymes** [comment]
Hi, glad you managed to resolve your issue. I think your use case is quite a specific use case. One thing you could do is add your [custom css or scripts](https://github.com/chrisrhymes/bulma-clean-theme#scripts) to the `_includes/head-scripts.html` file.
