### ISSUE TITLE
Issue with width of code block when the code contains long lines

### ISSUE THREAD

**Issue by grigorigoldman** [chrisrhymes/bulma-clean-theme#11]
When adding a code block to a blog post with very long lines because the width of the div is set to 100%, it causes the content to go off the page. 

Instead, the code block width should be the same as the other content on the page. The div already has overflow set to auto, so it will be horizontally scrollable, I believe.

**Comment by chrisrhymes** [comment]
I've set the width of the container column now so this should be prevented and the code block should now scroll as expected. 

#12

Please use the latest master branch or v0.5.5 of the gem for these changes. 

Let me know if this resolves your issue or send me a link so I can take a look in more detail.

**Comment by grigorigoldman** [comment]
Yes, this solves the issue. Thank you.
