### ISSUE TITLE
Inconsistent version number for release v0.12

### ISSUE THREAD

**Issue by emranbm** [chrisrhymes/bulma-clean-theme#110]
Hi,
Thanks for the awesome theme.  

I've discovered that there's a typo in the latest release tag ([version 0.12](https://github.com/chrisrhymes/bulma-clean-theme/releases/tag/v.0.12)). As you may see the release title is **v0.12**. But when I tried to use it like:
```yml
remote_theme: chrisrhymes/bulma-clean-theme@v0.12
```
encountered the error:
```
jekyll 3.9.0 | Error:  404 - Not Found - Loading URL: https://codeload.github.com/chrisrhymes/bulma-clean-theme/zip/v0.12
```
I noticed that the real tag name has an extra dot (`v.0.12`) and the release title (`v0.12`) was misleading.  
Please consider fixing it to save the others from such a mistake.  

Thanks a lot.  
Emran

**Comment by chrisrhymes** [comment]
Thanks for pointing this out! I will update the tag.

**Comment by chrisrhymes** [comment]
I have now replaced the v.0.12 tag with v0.12. Thanks.
