### ISSUE TITLE
Incorporating AdSense into the theme?

### ISSUE THREAD

**Issue by ghar-nainital** [chrisrhymes/bulma-clean-theme#131]
Hi,
Thank you for your work. Its indeed looks great and is very customizable. My query was that some jekyll themes support google adsense via
```
adsense:
  client_id: 'ca-pub-XXXXXXXXXXXX' # Google Adsense client ID
  auto_ads: true
```
This doesn't work out of the box for this theme so I was wondering what specific changes might be needed to incorporate google adsense into this theme. Thank you. Best.

**Comment by chrisrhymes** [comment]
Hi, sorry for the late reply to this. I can't comment specifically for Google adsense, but you can add your own custom scripts using the head-scripts.html and footer-scripts.html include files. https://www.csrhymes.com/bulma-clean-theme/docs/getting-started/scripts/#adding-scripts

You would then need to customise the page and/or post layouts if you need to insert html inside the template. You can do this by overriding theme defaults: https://www.csrhymes.com/bulma-clean-theme/docs/getting-started/scripts/#adding-scripts
