### ISSUE TITLE
Add site search functionality

### ISSUE THREAD

**Issue by CagedEther** [chrisrhymes/bulma-clean-theme#138]
Is it possible to add site search functionality to this theme (say in the top right) so that people can search the GH Pages site for information?

**Comment by magoerlich** [comment]
https://www.csrhymes.com/bulma-clean-theme/docs/getting-started/theming/#overriding-theme-defaults

**Comment by chrisrhymes** [comment]
Hi @CagedEther sorry for the delay in responding. As there are many options for implementing search functionality, and can become quite complex, I won't include this in the theme. 

However, I managed to implement Google Search on my personal site, so feel free to take a look at the changes I made [here](https://github.com/chrisrhymes/chrisrhymes.github.io/commit/2834d2e8526e71614080bfae42f9f3b4f5bb9e61) for some inspiration.

**Comment by CagedEther** [comment]
Hi Chris,

I'm having trouble making updates to my site. This was working 3 months ago
and I haven't changed anything since.

You can see the backend here:
GitHub - CagedEther/Nustory: Nustory Open Innovation Foundation
<https://github.com/CagedEther/Nustory>

These are the latest updates:
Workflow runs · CagedEther/Nustory · GitHub
<https://github.com/CagedEther/Nustory/actions>

I did try changing to GitHub Actions but this also failed:
https://jekyllrb.com/docs/continuous-integration/github-actions/

Do I need to update to a new version of the theme?

I don't have much experience with Jeckyl or gem files so appreciate any
guidance you can provide.

Many thanks,


Daryl
