### ISSUE TITLE
Customize Hero area

### ISSUE THREAD

**Issue by Hunv** [chrisrhymes/bulma-clean-theme#143]
Hi,
first of all: thank you for your great theme. It is really well documentated and works well for me so far.
I have one question because it looks like this cannot be done out-of-the-box:
I like to disable the linear-gradiant of the hero-area to have just a solid color. I modified the hero.sass and tried to put it in all places at the whole file tree but it is still the standard look.
Can you help me where exactly I have to put the modified hero.sass to overwrite the one from the theme?
My intention would be `root/_sass/layout`, but that is not working.

Note: this is my first try to build a page using Jekyll, so maybe it is very obvious and I just didn't find the correct answer or misinterpreted it.

**Comment by Hunv** [comment]
OK, I worked around this, by creating a 1x1 image-pixel with the color I want and set this as the background using this in the header:

`hero_image: /assets/images/bluepixel.png`

**Comment by chrisrhymes** [comment]
Hello, thanks for the feedback on the theme. 

The hero has the class 'is-bold' which adds the linear gradient. I tried looking on the Bulma docs site to show you, but it seems there is no reference to it anymore. Maybe it's been deprecated? 

Glad you managed to find a way around the issue.
