### ISSUE TITLE
Dependency version mismatch on Github Pages

### ISSUE THREAD

**Issue by Photon89** [chrisrhymes/bulma-clean-theme#147]
When trying to update from version 0.13.1 to 0.13.2 (or 0.13.3) on a Jekyll site which is deployed using GitHub Pages, I get the following problem:

```
11:08:28 AM: Fetching gem metadata from https://rubygems.org/...........
11:08:28 AM: sass-embedded-1.62.1-x86_64-linux-musl requires rubygems version >= 3.3.22,
11:08:28 AM: which is incompatible with the current version, 3.1.2
11:08:28 AM: Error during gem install
11:08:28 AM: Failing build: Failed to install dependencies
```

According to https://answers.netlify.com/t/rubygems-version-outdated-cannot-deploy/83652/5 this can be fixed by adding 

```
gem "jekyll-sass-converter", "~> 2.0"
```

to the Gemfile. However, when trying this, I get:

```
11:11:35 AM: Fetching gem metadata from [https://rubygems.org/.](https://rubygems.org/)
11:11:35 AM: You have requested:
11:11:35 AM:   jekyll-sass-converter ~> 2.0
11:11:35 AM: The bundle currently has jekyll-sass-converter locked at 3.0.0.
11:11:35 AM: Try running `bundle update jekyll-sass-converter`
11:11:35 AM: If you are updating multiple gems in your Gemfile at once,
11:11:35 AM: try passing them all to `bundle update`
11:11:35 AM: Error during gem install
11:11:35 AM: Failing build: Failed to install dependencies
```

I assume that changing the jekyll-sass-converter version to 2.0 in Gemfile.lock isn't a good idea, right? Is there anything that can be done to deploy the update in GitHub Pages?

Thanks!

**Comment by chrisrhymes** [comment]
Hello, have you tried including the [github-pages gem](https://github.com/github/pages-gem) locally and see if you can debug the issue locally? Also, it's worth checking what version of Jekyll are you using as GitHub pages only supports 3.9.x and not 4. 

If you want to use Jekyll 4 then there are alternative ways to deploy using GitHub actions now instead. Some information is available here: https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by DarthGandalf** [comment]
@Photon89 we're not using github pages there, but netlify. Netlify starts from installing deps using `bundle`, including jekyll v4.2.2

Have you tried running bundle update as advised in the error message?

**Comment by magoerlich** [comment]
You forgot applying half of the fix you linked yourself: 
>  by adding the following line to gemfile **(and then running bundle install):**
