### ISSUE TITLE
Can't find stylesheet to import

### ISSUE THREAD

**Issue by marcello-dev** [chrisrhymes/bulma-clean-theme#158]
Hi, 

Upgrading to v1 I get the following error: 
![image](https://github.com/chrisrhymes/bulma-clean-theme/assets/55074569/f28993ed-7b1d-417c-a164-0109cc497631)

The content of the file app.css is:
```
---
---
$primary: #F27100;
@import "main";
```
I have that file on my website because I changed the default color as [mentioned in the doc](https://github.com/chrisrhymes/bulma-clean-theme/blob/a764aec0a112d024197fa5950048523fa1832957/docs/getting-started/theming.md?plain=1#L21-L31).

Do you know what could be the issue?

**Comment by chrisrhymes** [comment]
Hi, I'm afraid I haven't seen this before. Maybe check what path is set for your sass source_dir in your _config.yml and if it is set to `_sass` where the `_main.scss` file is?

```yaml
sass:
  style: compressed
  source_dir: _sass
```

**Comment by marcello-dev** [comment]
I don't have a path set for sass. This is my config.yml file: https://github.com/marcello-dev/marcello-dev.github.io/blob/feature/upgrade-to-bulma1/_config.yml

**Comment by marcello-dev** [comment]
I could fix it with this PR: https://github.com/marcello-dev/marcello-dev.github.io/pull/2/files And also by setting up Github Actions.
But there are still some issues. 
- The local version seems to differ from the deployed one. Locally the dark mode works, but not on the deployed version. 
- The font color of the Hero has always been white, but locally it changed to black (See below)
Local version:
![image](https://github.com/chrisrhymes/bulma-clean-theme/assets/55074569/570c8c6f-e607-4ed9-8d87-6d958d5f03b6)
Deployed version:
![image](https://github.com/chrisrhymes/bulma-clean-theme/assets/55074569/840e442c-9ede-4dc6-9490-3bf7568ae644)

Do you have an idea how to fix these issues? 
I think the migration doc is very limited, please consider to add more info. Moving away from [github-pages](https://rubygems.org/gems/github-pages) is not straightforward.

**Comment by chrisrhymes** [comment]
Glad you managed to get the upgrade sorted. 

With regard to the hero text colour, this may be to do with Bulma v1's themes that have been introduced. There is some information in the [upgrade guide](https://www.csrhymes.com/bulma-clean-theme/docs/getting-started/upgrading-to-v1/#changes-to-bulma) to force using the light theme.

Please also see more information on the Bulma framework site as well regarding the dark mode. 
https://bulma.io/documentation/features/dark-mode/

For GitHub actions, I agree it is more complicated than using the previous method to deploy. What do you think needs to be added to the upgrade guide?

**Comment by marcello-dev** [comment]
The issue I am having is on the light mode. The dark mode seems fine.

**Comment by chrisrhymes** [comment]
I have been looking at the [hero examples](https://bulma.io/documentation/layout/hero/) on the Bulma website and it looks like the black text is the desired behaviour in v1 of Bulma as most have dark text rather than white. This could be to improve colour contrast to meet accessibility guidelines.  
<img width="393" alt="Screenshot 2024-05-26 at 20 44 02" src="https://github.com/chrisrhymes/bulma-clean-theme/assets/4160546/c1cef90c-864b-4565-9716-d08d0c018388">
<img width="396" alt="Screenshot 2024-05-26 at 20 43 49" src="https://github.com/chrisrhymes/bulma-clean-theme/assets/4160546/f8e1b67b-4c27-4431-83b2-f80a6460efeb">

**Comment by marcello-dev** [comment]
I see, thank you for checking. Can close the issue if you want.
