### ISSUE TITLE
bulma-clean-theme defaults to version 0.3 when run locally with github-pages gem

### ISSUE THREAD

**Issue by risa2000** [chrisrhymes/bulma-clean-theme#16]
I am facing a strange problem. I have been testing locally my site with `bulma-clean-theme` using this `Gemfile`:
```
source 'https://rubygems.org'
gem 'github-pages'
gem 'bulma-clean-theme'
```
Running `bundle install` resolves `bulma-clean-theme` to version 0.3. I am attaching the full Gemfile.lock here [Gemfile.lock.txt](https://github.com/chrisrhymes/bulma-clean-theme/files/3606514/Gemfile.lock.txt). This file is from the Windows tests, but on Gentoo the file is basically the same, except it misses `x64-mingw32` flavoring.

If I try to force the latest version of the theme in Gemfile:
```
source 'https://rubygems.org'
gem 'github-pages'
gem 'bulma-clean-theme', '0.5.6'
```
`bundle update` fails with some unresolved dependencies:
```
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    bulma-clean-theme (= 0.5.6) was resolved to 0.5.6, which depends on
      jekyll (~> 3.8)

    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

Bundler could not find compatible versions for gem "rouge":
  In Gemfile:
    bulma-clean-theme (= 0.5.6) was resolved to 0.5.6, which depends on
      rouge (~> 3.3)

    github-pages was resolved to 198, which depends on
      rouge (= 2.2.1)
```
Now, I have tried this on Windows and on Gentoo with almost the same results (Windows version gives also an unresolved dependency on `ruby` on top). But all those versions seem so ancient that I suspect there is some bug in the dependency definition.

So at the moment, I am running the theme locally with 0.3 version, but when I set the theme as `remote-theme` in a GitHub repo (https://risa2000.github.io/testpages/) it generates a page, which seems to be using the newer version of the theme because the layout (e.g. the footer section) corresponds to the newer version found in 0.5.6.

Now I am not sure, how to test the theme locally, and how to find out, which version is used when GitHub pages are generated directly from the repo.

I am also not sure, if this is a problem with the theme or `github-pages` gem, but would like to figure it out, so I could use the same version of the theme locally as the one which GitHub uses (and which `github-pages` gem is actually supposed to ensure).

Any ideas?

**Comment by chrisrhymes** [comment]
I don't think you need the github-pages gem for it to work with GitHub pages so I would remove it from your Gemfile and run `bundle update` to rebuild the Gemfile.lock. 
For the layout, you should set it to `layout: page` rather than default, as page extends default.

**Comment by risa2000** [comment]
Yes, it seem so, though I originally installed jekyll-4.0.0 and with it had a bunch of dependencies pulled in, which did not go well with `github-pages` gem at all, so I got scared and did not want to experiment much ;). Anyway, thanks for the help and for merging my PR.
