### ISSUE TITLE
Changing colors of text in navigation bar

### ISSUE THREAD

**Issue by ajallenunc** [chrisrhymes/bulma-clean-theme#160]
Hello, 

I am trying to change the color of the text in the navigation bar. I have added these lines to my `/assets/css/app.scss` file

```
---
---
$primary: #77c0f7;
$navbar-background-color: #000000;
$navbar-item-active-color: #000000;
// Import Main CSS file from theme
@import "main";
```

The primary color changes properly, however the text in the navbar is still white instead of black. I've tried a few different sass variables [here](https://bulma.io/documentation/components/navbar/#colors) with no luck. Any guidance would be appreciated. Sorry if this is the wrong place for this question.

**Comment by chrisrhymes** [comment]
Hi @ajallenunc it's probably worth asking this question in [bulma issues](https://github.com/jgthms/bulma/issues) as I believe the navbar-link colour is set to contrast the $primary colour.
