### ISSUE TITLE
The product category layout does not allow to override the collection.

### ISSUE THREAD

**Issue by jcm236** [chrisrhymes/bulma-clean-theme#164]
I have a website here:  [repo](https://github.com/PluginSmiths/pluginsmiths.github.io/tree/main)
In the ```_config.yml``` file I have set software to be a collection and set the collection variable in ```plugins.md``` to software. But the build fails if I do this. If I add products as a collection in the config file but keep collection as software in plugin.md, the build is successful.
How do I override the default collection for products?

**Comment by jcm236** [comment]
The code for the product category layout overrides the collection to page.collection if it exists. But page.collection means the page has to be in the same collection as the product. Ref: [Variables](https://jekyllrb.com/docs/variables/)

**Comment by chrisrhymes** [comment]
Please can you try updating the _config.yml to use version v1.0.4 in the remote theme as this was only added recently. I will work on updating the docs to state this.

**Comment by jcm236** [comment]
Could you please provide an example product category page with a collection override?

**Comment by jcm236** [comment]
I have updated the version of the theme to 1.0.4

**Comment by jcm236** [comment]
I have implemented a fix [here](https://github.com/jcm236/jcm236.github.io)

**Comment by jcm236** [comment]
I will open a PR to merge it

**Comment by jcm236** [comment]
If this is merged, which version of the theme will I have to update to?

**Comment by chrisrhymes** [comment]
Hi. Please use 1.0.4. You don't need to edit the theme files, just add the name of your collection to the category page. Please see the documentation here. 

https://www.csrhymes.com/bulma-clean-theme/docs/products/category-page/

**Comment by jim79** [comment]
I have tried this with 1.0.4. The collection variable is used by jekyll as stated here: https://jekyllrb.com/docs/variables/

**Comment by jcm236** [comment]
Thank You! It works now. Also because the main theme did not have it, I added a progress bar to my fork. It's not been pushed to GitHub yet but I could open a PR If you like.
