### ISSUE TITLE
Reflexion on my recent bulma-clean-theme adaptation

### ISSUE THREAD

**Issue by risa2000** [chrisrhymes/bulma-clean-theme#17]
@chrisrhymes I have been hacking your theme lately for my two projects and thought I might give you some feedback on some points I changed or added. I am not creating a PR for that because I am not sure if it is really "pullable" in the current state, and if it is even possible to make it general enough so it is worth adding to the theme. Nevertheless here is what I did:

1) I have changed the `_includes/header.html` and removed `site.title` from the nav menu. I found it confusing to have two buttons (`site.title` and `Home`) pointing to the same URL i.e. root. Plus in one of my project, I have also an additional custom menu item (with a drop down menu) which also points to the root (https://risa2000.github.io/vrdocs/) so it became mega confusing.

Originally I thought about using `site.title` only (and `Home` when `site.title` was not defined), but  it turned out to be confusing too. On the project given above it would give `VR Docs` and `Docs` buttons both pointing to the root, the former just doing "less". So I finally decided to keep just `Home` (and made it the prominent button in the layout). You can find the changed file (and others) in my project repo here (https://github.com/risa2000/vrdocs/tree/master/_includes).

2) I have changed the footer too, because I liked the one you put on your personal site, so I just modified it to include my license. What I also did though was deliberately changing the href to `bulma-clean-theme` which originally pointed to the Ruby Gem repository to point to the GitHub repo. I thought that if anyone find the style appealing, he would probably want to know more about the style and I thought it would be better answered by the GitHub repo info than by the Gem statistics.

3) I have "hacked" your `_includes\menubar.html` and added the TOC (of the current page) from @allejo (https://github.com/allejo/jekyll-toc) to the menubar nav pane. The TOC is created when both `page.menubar` and `page.menubar_toc` are set. You can see how it looks here (https://risa2000.github.io/vrdocs/docs/hmd_fov_calculation.html). There is a possibility to have also the site menubar above the TOC (if it is defined in YAML), but at the moment I am not using it as I do not need it.

I would say this one would be a good candidate for an addition, except that the TOC script offers several user configurable options, some of which could be hardcoded, but most should be left exposed to the user, and I do not know, if or how it could be done.

**Comment by chrisrhymes** [comment]
Thanks for your feedback @risa2000 . I will definitely have a think about the duplicate home links and the footer. I hadn't heard about jekyll-toc before but this looks great. I will think about how to implement this in the next release.
