### ISSUE TITLE
ERROR `/favicon.png' not found.

### ISSUE THREAD

**Issue by marcello-dev** [chrisrhymes/bulma-clean-theme#19]
This error shows up when serving the website with the command:
`bundle exec jekyll serve`
I think is because the favicon.png file is hardcoded here:
https://github.com/chrisrhymes/bulma-clean-theme/blob/42dcd22e22fd3fda558c5977ed10464cc5f15908/_includes/head.html#L6

If I download the favicon.png from your repo and put it in my project folder, then the error disappears. But what if I want to change the shortcut icon?

**Comment by chrisrhymes** [comment]
Hi, 

Thanks for reporting this. I added the favicon url from [this pull request](https://github.com/chrisrhymes/bulma-clean-theme/pull/13). I intended to package a default favicon with the theme but it doesn't seem to have worked so I'll take a look at that when I can. 

Do you think it would be useful to have a variable in the `_config.yml` to overwrite the default favicon path? Something like:
```yaml
favicon: path/to/favicon.png
```

Then update the head.html to the following:
```html
 <link rel="shortcut icon" type="image/png" {% if site.favicon %} href="{{ site.favicon | prepend: site.baseurl }}" {% else %} href="{{ site.baseurl }}/favicon.png" {% endif %} /> 
```

**Comment by marcello-dev** [comment]
Yes, this fix looks good, thanks! 
In the README you can specify that **png** is the extension supported for now. Unless you want to parametrize it too.

**Comment by chrisrhymes** [comment]
@marcello-dev I've updated the readme as suggested and also added the ability to override the default.
