### ISSUE TITLE
Blog layout not surfacing post-card include

### ISSUE THREAD

**Issue by Yecats** [chrisrhymes/bulma-clean-theme#21]
I just pulled in your theme to a brand new GitHub repository. I noticed that it came with four posts in the _posts folder (which surface if I turn the side bar on) but they do not seem to be registering on the blog page. This is what I see:

![image](https://user-images.githubusercontent.com/4108756/67222934-2f684880-f3e3-11e9-9d28-9021e22597f1.png)

The code is all standard with your repository (I haven't changed anything) and looks to be correct so I am at a loss.

**Comment by chrisrhymes** [comment]
Hi @Yecats thanks for the feedback. I have now updated the readme for posts https://github.com/chrisrhymes/bulma-clean-theme/blob/master/README.md#posts
