### ISSUE TITLE
Keep receiving a warning by mail for page building

### ISSUE THREAD

**Issue by Funeoz** [chrisrhymes/bulma-clean-theme#23]
The build is working but keep receiving a mail saying : "You are attempting to use a Jekyll theme, "bulma-clean-theme", which is not supported by GitHub Pages.". Should i change the "theme:" setting in *_config.yml* to "remote_theme:" ?

**Comment by chrisrhymes** [comment]
When working locally I set my _config.yml as follows with both remote-theme and theme.

```yaml
theme: bulma-clean-theme
remote-theme: chrisrhymes/bulma-clean-theme
```

and when I push to github pages I comment out the theme to avoid getting the warning email, but leave the remote theme setting
```yaml
#theme: bulma-clean-theme
remote-theme: chrisrhymes/bulma-clean-theme
```

I contacted github pages support about this in February this year and they said to use github-pages gem to resolve the issue, but at that time the gem required an old version of Jekyll. It looks like the latest version of github-pages gem now uses Jekyll 3.8.5.

**Comment by Funeoz** [comment]
So every time I work locally or I push my changes to GitHub, I need to modify these settings ?

**Comment by chrisrhymes** [comment]
This is what I do currently but it’s not ideal. I will try and add GitHub pages gem to a test site this weekend to see if this resolves the need for changing settings.

**Comment by chrisrhymes** [comment]
Thanks for bearing with me. 

It seems you can remove the need for `theme: bulma-clean-theme` in your `_config.yml` file completely if you add `gem 'github-pages', group: :jekyll_plugins` to your `Gemfile` and then add github-pages to your plugins in `_config.yml`

```yaml
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - github-pages
```

Then run `bundle update`. 

Now when you run `bundle exec jekyll serve` locally it should build using the specified `remote_theme` as per GitHub Pages build.

```bash
Generating... 
Remote Theme: Using theme chrisrhymes/bulma-clean-theme
           done in 4.43 seconds.
```

**Comment by Funeoz** [comment]
Okay, so I tried it and it seems to be working. But I get an error when running _bundle exec jekyll serve_: `Invalid theme folder: _sass`.
Is this folder needed or not ?

**Comment by chrisrhymes** [comment]
Glad its working for you. 
For the invalid theme folder message, it looks like this is a warning, rather than an error, from Jekyll when using a remote_theme instead of theme. 
https://github.com/jekyll/jekyll/issues/7630
