### ISSUE TITLE
Display posts from a category on blog layout

### ISSUE THREAD

**Issue by Funeoz** [chrisrhymes/bulma-clean-theme#24]
I would like to display some posts on a page that respond to a same subject like for exemple on my site (https://funeoz.github.io/techlovers/), the subject "Linux". Is is possible ?

**Comment by chrisrhymes** [comment]
Hi @Funeoz this looks similar to #4 is that what you are asking?

**Comment by Funeoz** [comment]
That was what I was looking for. Thank you.
