### ISSUE TITLE
Headings not showing up in "post" layout

### ISSUE THREAD

**Issue by vgoel** [chrisrhymes/bulma-clean-theme#3]
For some reason, headings are not showing up in the "post" layout. "page" layout works fine. (See attached md snippet and screenshot)

https://gist.github.com/vgoel/d9dc3bfb1ef629a54fe2e1aea43e3b1f

![2019-04-27-170357_1215x535_scrot](https://user-images.githubusercontent.com/1899679/56856455-92cf5d00-690f-11e9-8762-98a46c2b1657.png)

**Comment by vgoel** [comment]
Also tried with the default config. Steps:
- git clone bulma-clean-theme repo
- Add a heading to "Test Post 3"


title: Test Post 3
subtitle: Test post subtitle
layout: post
author: C.S. Rhymes
tags: html JavaScript CSS Jekyll
---

# TEST POST 3
This is a test post! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sollicitudin ultrices eros id accumsan. Vestibulum dictum volutpat sapien in molestie. Nunc auctor felis quis nibh tincidunt, vel sodales dolor viverra. Donec elementum dolor nisl, nec imperdiet sapien semper in.


Screenshot:
![2019-04-27-174040_1258x598_scrot](https://user-images.githubusercontent.com/1899679/56856639-b694a200-6913-11e9-9221-a27642abc6a1.png)

**Comment by chrisrhymes** [comment]
Nice spot! Just pushed a fix for this in master branch / v0.5.1 ruby gem.
