### ISSUE TITLE
Change code blocks color

### ISSUE THREAD

**Issue by Funeoz** [chrisrhymes/bulma-clean-theme#30]
I would like to change code blocks for darker colors. Is it possible ? And also, put the code to the left of the block in the post layout.

**Comment by chrisrhymes** [comment]
The code styles are contained in the ‘_sass/syntax.scss’ file. You can try creating this folder and file in your site and it should overwrite the default file in the theme. 

I used [rougify](https://github.com/rouge-ruby/rouge/blob/master/README.md#command-line) to generate the current syntax.scss file so there may be another theme you prefer instead.

**Comment by Funeoz** [comment]
Okay, thank you. I will search for a good theme and change it.
