### ISSUE TITLE
customise font family

### ISSUE THREAD

**Issue by benswift** [chrisrhymes/bulma-clean-theme#34]
Hey there

Is there a way to customise the main font family, i.e. the `$family-sans-serif` bulma variable?

I've tried setting it (and importing the relevant style sheets to set up the web font) in `app.scss`, both before and after `@import "main"` but it doesn't seem to take effect. Is that because `$family-sans-serif` is one of only a couple of variables which is actually set in `_main.scss` (directly before importing the main bulma style sheet)?

**Comment by chrisrhymes** [comment]
Hi, 
In the next release I will update `$family-sans-serif` to be a `!default` sass variable so it can be easily overwritten. 

In the mean time, you can set `$family-primary` variable to your chosen font in `app.scss` before `@import "main"` to overwrite the font.

**Comment by benswift** [comment]
Ok, great - thanks. If setting `$family-primary` is better anyway then I'm happy to do that---I'm new to bulma and still trying to get my head around the "top level" variables to set.
