### ISSUE TITLE
Put codeblocks on the left

### ISSUE THREAD

**Issue by Funeoz** [chrisrhymes/bulma-clean-theme#35]
Is it possible to put the code on the left than centering it ?

**Comment by chrisrhymes** [comment]
Hello, I’m not sure I understand what your issue is. Can you post a code example or a link? Thanks

**Comment by Funeoz** [comment]
For example, in this codeblock: 
![image](https://user-images.githubusercontent.com/31157012/72662055-49192c00-39e2-11ea-85de-ba16d80d307b.png).
I would like that the code in this codeblock starts on the left and not from the center. Is it possible?

**Comment by chrisrhymes** [comment]
That’s strange. By default code blocks are left aligned, such as on this [page](http://www.csrhymes.com/bulma-clean-theme/landing/). Is the code block inside another div with the class `has-text-centered`?

**Comment by Funeoz** [comment]
Actually, when I search for the class ```has-text-centered```, I can only find it in 4 files that are ```_includes/callouts.html```, ```_includes/footer.html```, ```_includes/post-card.html``` and ```_includes/rating.html```. And I write my posts in Markdown so I can't really find the error.

**Comment by chrisrhymes** [comment]
Are you able to try the latest version of the theme (gem 0.6.5) and see if you are still having an issue? There were some styles being overridden by another package I was using.

**Comment by Funeoz** [comment]
After updating the gem, I still have the issue...
