### ISSUE TITLE
Typo in subscribe.html

### ISSUE THREAD

**Issue by SubashPadmanaban** [chrisrhymes/bulma-clean-theme#39]
Hello chrisrhymes, thank you so much for creating this theme. So far I've been loving it. I just noticed that there's a typo in `_includes/subscribe.html` where in line 4, the word subscribe is spelt incorrectly as `Subscrbe` with a missing `i`.

**Comment by chrisrhymes** [comment]
Thanks for letting me know and glad you like the theme! I've just pushed an update (gem version 0.6.5) where this is fixed.
