### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by vgoel** [chrisrhymes/bulma-clean-theme#4]
Any easy way to add Categories to the theme?  I see that tags are there but they are not clickable...

**Comment by chrisrhymes** [comment]
It looks like Jekyll doesn't support category pages by default. There are plugins available to do this, such as [this one](https://github.com/field-theory/jekyll-category-pages), but they are not on the list of [GitHub Pages supported gems](https://help.github.com/en/articles/adding-jekyll-plugins-to-a-github-pages-site) and I really want to ensure the theme can be used with GitHub Pages so I can't add it to the theme by default.
