### ISSUE TITLE
Problem with Jekyll-version 4.0 x bulma-clean-theme-version 3.8

### ISSUE THREAD

**Issue by laiscavalcanti** [chrisrhymes/bulma-clean-theme#40]
In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0) x64-mingw32

    bulma-clean-theme x64-mingw32 was resolved to 0.6.5, which depends on
      jekyll (~> 3.8) x64-mingw32

**Comment by chrisrhymes** [comment]
Hello, please see #26 the theme requires Jekyll 3.8 so it is compatible with [GitHub Pages gem](https://rubygems.org/gems/github-pages).
