### ISSUE TITLE
Pagination current background color doesn't update with primary color

### ISSUE THREAD

**Issue by philww241** [chrisrhymes/bulma-clean-theme#47]
The background color for the current page number in the blog index page (eg http://www.csrhymes.com/bulma-clean-theme/blog/) doesn't change with the rest of the site after changing the $primary color in app.scss. See screengrab below for an example. 

This is not exactly a bug (even though the result looks odd), because it is a link and therefore correctly uses the $link color. The fix therefore is to add a new sass variable in app.scss to set the $link color: 

```
---
---
$primary: #333333;
$link: #333333;
// Import Main CSS file from theme
@import "main";
```
I thought it might be worth adding a note about this under 'Colours and Styles' in the readme.

![image](https://user-images.githubusercontent.com/66526406/84605701-40485b80-ae97-11ea-9057-bb51d7877e33.png)

**Comment by chrisrhymes** [comment]
Hello. I tried to leave the theme styling as minimal as possible. As you said, you can customise the link variable, or if you prefer you can specifically customise Bulma pagination variables as you need. 

https://bulma.io/documentation/components/pagination/

**Comment by philww241** [comment]
That's fair enough. I found the theme very easy to work with, it was just that one aspect that puzzled me until I figured out how to solve it.
