### ISSUE TITLE
What is the best way to incorporate Bulma-extensions and change layout?

### ISSUE THREAD

**Issue by limsherwin** [chrisrhymes/bulma-clean-theme#52]
Hello,

I would like to use some of the bulma-extensions (bulma-carousel, bulma-calendar). I would also like to add images and rearrange the layout of the callouts (as shown in the attachments).

Is there a way to do this elegantly? I am concerned that if I override the theme as explained [here](https://jekyllrb.com/docs/themes/), something might break when the Bulma Clean Theme updates.

Cheers,
Sherwin

![Screenshot_20200713_113840a](https://user-images.githubusercontent.com/941004/87295348-9f050180-c537-11ea-9caa-0ef786939e99.png)

![Screenshot_20200713_113814a](https://user-images.githubusercontent.com/941004/87295325-990f2080-c537-11ea-9b90-08acb307c629.png)

**Comment by chrisrhymes** [comment]
Hi @limsherwin, If the desired layouts are very different from the original theme then it might be better to choose a different theme or fork this theme and then make your changes. There is no real way to easily get future updates if you make large changes to the base theme. Thanks

**Comment by limsherwin** [comment]
Thanks @chrisrhymes. I'll try to find a way to continue using your theme. I'm already knee deep in Jekyll and Bulma.
