### ISSUE TITLE
I writed many posts but blog index not display posts

### ISSUE THREAD

**Issue by whaleluo** [chrisrhymes/bulma-clean-theme#54]
![image](https://user-images.githubusercontent.com/39004920/90202439-b118df00-de18-11ea-9a3b-3e3d1e69828e.png)

**Comment by chrisrhymes** [comment]
Hello. Have you tried the following?

Set the paginate and the paginate_path up in the _config.yaml to configure the posts per page and the blog pagination path.

paginate: 5
paginate_path: "/blog/page:num"

**Comment by whaleluo** [comment]
thank you very much ,chrisrhymes , is ok !
