### ISSUE TITLE
Hyperlinking Images in Image Gallery to Other Pages

### ISSUE THREAD

**Issue by TheNeeloy** [chrisrhymes/bulma-clean-theme#55]
Hey Chris!

I'm really enjoying using your bulma clean theme, and its powerful functionalities.
I recently added an image gallery to my personal website using the syntax you provided and it's looking good.

Was wondering, is there a way to add hyperlinks to the images in the image gallery so users can click on images and be brought to another page? 

I've tried using markdown syntax by setting each `link` attribute under the `images` section in the gallery.yml file to something in the form of `[![Alt text](/path/to/img.jpg)](http://example.net/)`, but this throws an error in the building of the site.

**Comment by chrisrhymes** [comment]
Interesting idea. For now you can add a link to the image description as it accepts markdown, but this would only be a text link.

**Comment by chrisrhymes** [comment]
Hi,

I know this isn't exactly what you have asked for but thought it might interest you.

I've just pushed an update (gem version 0.9.2) that has an image-modal include. You can include the image modal in a page (but it needs to be a html page) or make use of the image gallery. The image gallery has been updated to allow clicking on the image to see a larger version in a modal.

**Comment by TheNeeloy** [comment]
Cool, I'll try it out!
