### ISSUE TITLE
Regarding Jekyll version 4

### ISSUE THREAD

**Issue by cbmgit** [chrisrhymes/bulma-clean-theme#56]
I loved this theme and trying to test in local env and I was facing this error.

`Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (~> 4.1.1)`

   ` bulma-clean-theme was resolved to 0.9.1, which depends on
      jekyll (~> 3.8)`

When I have changed to version 3.8, it's working fine. Just curious to know when version 4 will be supported for this theme? or is there any way to use 4.1.1 by changing some configuration?

**Comment by chrisrhymes** [comment]
Hi @cbmgit I'm keeping this theme compatible with GitHub Pages gem which still uses Jekyll 3.8.
