### ISSUE TITLE
Add images to posts with click to enlarge function

### ISSUE THREAD

**Issue by currentsauce** [chrisrhymes/bulma-clean-theme#58]
Hi Chris,

I am looking for a way to be able to add images of any dimension within a post, and have it display at a suitable size, and then be able to open the full size image by clicking on it (maybe even scroll through the images, though that would be a bonus).

I can't seem to be able to do that right now with markdown, and to do it with HTML requires some javascript, I think? 

Do you have any suggestions or work-arounds for this please?

Thanks very much!

James

**Comment by currentsauce** [comment]
I should probably add, that it is possible to add images and embed them within a hyperlink to open them in full, I'm aware of that. 

Reason for asking, is I wanted to know if there is a more elegant way than that before I start embedding them the above way. 

I'm sure there must be a way of adding some more java script and then having the compiled html use that via some markdown liquid code? I've been trying myself but not had much luck.

Thanks again, 

James

**Comment by chrisrhymes** [comment]
Hi,

I've just pushed an update (gem version 0.9.2) that has an image-modal include. You can include the [image modal in a page](https://www.csrhymes.com/bulma-clean-theme/page-with-image-modal/) (but it needs to be a html page) or make use of the [image gallery](https://www.csrhymes.com/bulma-clean-theme/gallery/). The image gallery has been updated to allow clicking on the image to see a larger version in a modal.

**Comment by currentsauce** [comment]
Looking promising Chris, thank you!

For the image gallery, is there a way of controlling where on the page it appears? I'd really like to be able to write posts and break up the text with pictures in between, to show visually what is being talked about in the text - hopefully that makes sense?

The image modal looks like a good way of doing this, though wanted to avoid writing HTML. Though may go down this route if the above isnt do-able.

Thanks again!

**Comment by currentsauce** [comment]
Still interested in the ability to chose where to insert galleries, but I just tried out image-modal, and either I have something wrong, or it's a bug. My money is on the former!

![2020-10-05 22_12_36-Blog - Current Sauce](https://user-images.githubusercontent.com/64914821/95132576-ec1ffa80-0757-11eb-8791-368b32199d1b.png)

**Comment by chrisrhymes** [comment]
Hi, the excerpt is taken automatically from the post. I think it normally takes the first section of the post. It might be worth adding an introduction paragraph to the page so this is used as the excerpt in the blog page.

**Comment by currentsauce** [comment]
Was this reply meant for issue 61? What I was talking about here is the "Read More" button showing in the wrong place for `html` posts.

**Comment by currentsauce** [comment]
Also, for completeness, here is what I settled on for including images.

1. Added a file `image.html` to my `_includes`:
```
<figure style="border: 1px solid #ccc; padding: 5px">
   <a href="{{ include.LargeImg }}">
   <img src="{{ include.SmallImg }}" style="max-width: {{ include.max-width }};"
      alt="{{ include.alt }}"/>
   </a>
   <figcaption>{{ include.caption }}</figcaption>
</figure>
```



2. In the post markdown file, use the following:
```
{% include image.html 
SmallImg="/path/to/smallimage" max-width="200px" 
LargeImg="/path/to/largeimage" 
alt="Alt text"
caption="This is the caption." 
%}
```

It works well for me, and despite relying on the browser back button, I'm happy with it. Though I suspect a professional web developer such as yourself might have a different opinion... 😬

**Comment by chrisrhymes** [comment]
I believe the read more button was showing in the wrong place due to additional html tags being included in the excerpt, rather than just a paragraph, but glad you got the large image solution sorted.
