### ISSUE TITLE
updating to bulma 7.5

### ISSUE THREAD

**Issue by edwardbattistini** [chrisrhymes/bulma-clean-theme#6]
Would it be possible to update the theme to bulimia 7.5 ?

**Comment by chrisrhymes** [comment]
The theme has been updated to the latest version of Bulma in https://github.com/chrisrhymes/bulma-clean-theme/pull/7

Please use the latest master branch or [gem version 0.5.2](https://rubygems.org/gems/bulma-clean-theme)

Thanks
