### ISSUE TITLE
Latest Posts sidebar is including the footnotes

### ISSUE THREAD

**Issue by currentsauce** [chrisrhymes/bulma-clean-theme#61]
Hi,

I have noticed that when the latest posts are shown in the side bar, it is including the footnotes.

![footnote](https://user-images.githubusercontent.com/64914821/95464839-53b19200-0972-11eb-977f-fc5fe2c00506.png)

I've tried to trace this, and it seems to be coming from what is generated for `{{ post.excerpt }}` in `post-card.html` - I've not yet figured how to amend what is generated for `{{ post.excerpt }}`.

For now, I've added post-card.html to `_includes` and commented out  `<p>{{ post.excerpt }}</p>`

Any input appreciated, cheers,
James

**Comment by chrisrhymes** [comment]
You could try replacing `{{ post.excerpt }}` with `{{ post.excerpt | strip_html }}` to see if this removes the footnotes.

**Comment by currentsauce** [comment]
Thanks Chris, i'll give it a go.

Just thought of an alternative idea, create an item in the post's front matter to define a sort of post-card-teaser text that is used in the post-cards. Only just come into my head so not yet investigated doing that, so any pointers or heads-up would be good welcomed :)

**Comment by chrisrhymes** [comment]
Hi @currentsauce v0.10.1 allows you to overwrite the default excerpt with a custom post summary. 
https://github.com/chrisrhymes/bulma-clean-theme#post-excerpt-and-summary
