### ISSUE TITLE
Only local resources

### ISSUE THREAD

**Issue by jze** [chrisrhymes/bulma-clean-theme#64]
To protect website visors best from tracking it would be beneficial if no resources would be loaded from third-party websites. Currently `alpine.min.js` is loaded from an external source. A strict interpretation of the EU's GDPR does no allow the transfer of personal information (such as the IP address) into a non-EU country without the user's consent. So I don't have a good feeling about it.

A simple solution would be a local copy of `alpine.min.js` in the `assets/js/` directory. However, eventually that copy will be outdated. Ideally, an up-to-date copy would be created when the website is processed by Jekyll. I have just started using Jekyll, so I am not sure if that would be possible.

**Comment by chrisrhymes** [comment]
Hi @jze, thanks for your comment. It's standard practice to use a CDN for resources like this:
https://developer.mozilla.org/en-US/docs/Glossary/CDN
