### ISSUE TITLE
Icons not showing up properly

### ISSUE THREAD

**Issue by LittleKitacho** [chrisrhymes/bulma-clean-theme#65]
![image](https://user-images.githubusercontent.com/40306561/96012645-4f71f280-0e12-11eb-9ec9-e30832eae550.png)

The icon is way too close to the title, making it look off.

![image](https://user-images.githubusercontent.com/40306561/96012750-73cdcf00-0e12-11eb-9c8a-b3e8799bc319.png)

This also shows up on the example page, so it is not a local issue.

**Comment by chrisrhymes** [comment]
Hi @LittleKitacho, v0.10.1 should resolve this issue for you.

**Comment by LittleKitacho** [comment]
Looks much better, thank you!
