### ISSUE TITLE
[feature request] adding theme-color in the head section

### ISSUE THREAD

**Issue by kalwalt** [chrisrhymes/bulma-clean-theme#71]
I want to add the theme-color to the head section, so i customized the `head-script.html` with this line of code:

`<meta name="theme-color" content="#157878">`

But i think would be nice add this line in the `head`  section by default adding a **theme_color** variable in the `_config.yml`:

```html
// inside the head section!
<meta name="theme-color" content={{ site.theme_color }}>

// somewhere in _config.yml
theme_color: #157878
```

**Comment by chrisrhymes** [comment]
This has been added in v0.10.3

**Comment by kalwalt** [comment]
Thank you! very appreciated!
