### ISSUE TITLE
gh-pages fails to build

### ISSUE THREAD

**Issue by kalwalt** [chrisrhymes/bulma-clean-theme#72]
I followed your instructions in your repository and in _config.yml i added:

`remote_theme: chrisrhymes/bulma-clean-theme`

but when i pushed to github i receive this error and the  webssite is not build see the picture.
![gh-pages-fails](https://user-images.githubusercontent.com/1275858/98876469-a94ff180-247e-11eb-87b7-672880ee8d3c.png)
What i'm doing wrong?
You can find the source code here: https://github.com/webarkit/webarkit.github.io
I will appreciate if you can help me with this issue. :slightly_smiling_face:

**Comment by kalwalt** [comment]
i still receive this error: 
`Your site is having problems building: The bulma-clean-theme theme is not currently supported on GitHub Pages. For more information, see https://docs.github.com/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.`
I'm serving the site from gh-pages now, I tested my `_config.yml` with a yaml validator, and it is ok. Could be caused by some bad formatting code?

**Comment by chrisrhymes** [comment]
Hello @kalwalt from your commit history I'm guessing you have resolved this now? It looks like you were missing bulma-clean-theme from your gemfile?

**Comment by kalwalt** [comment]
Hi @chrisrhymes i solved switching to Netlify services, although i really don't understand the issue, because initially i had the gem. Maybe i will test in another repositroy. Anyway thank you for the answer, and thank you for this nice theme! I am a big fan of Bulma... :smile: :sunglasses:
