### ISSUE TITLE
Tags for posts

### ISSUE THREAD

**Issue by DarthGandalf** [chrisrhymes/bulma-clean-theme#82]
Could click on a tag in a blog post link to a paginated list of posts with this tag?

Also the main page for the blog should probably contain a list of such tags to click.

Perhaps based on https://github.com/jekyll/jekyll-archives

**Comment by chrisrhymes** [comment]
Hi @DarthGandalf I want the theme to be compatible with GitHub Pages, which only supports [certain plugins](https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins) so I don't think what you are asking for is available with the supported plugins. If you are not using GitHub pages for your hosting then feel free to add the plugins you want to use and customise the theme to suit your needs using [overrides](https://jekyllrb.com/docs/themes/#overriding-theme-defaults).

**Comment by DarthGandalf** [comment]
I see, thanks!
