### ISSUE TITLE
Sensible {% highlight %} text alignment

### ISSUE THREAD

**Issue by maedi** [chrisrhymes/bulma-clean-theme#86]
The center alignment style on `.content figure` is not a sensible selector given that `{% highlight ruby %}` outputs `figure` for code highlighting. It outputs `figure.highlight` so there is a way to detect and avoid this situation with a more specific `.content figure:not(.highlight)` selector.

<img width="1360" alt="Screen Shot 2021-01-23 at 4 48 50 pm" src="https://user-images.githubusercontent.com/601650/105570112-49899700-5d9b-11eb-8e42-fc99cfd8103c.png">

**Comment by chrisrhymes** [comment]
Hi @maedi please can you post an example snippet from your markdown page so I can replicates this?

**Comment by chrisrhymes** [comment]
I have reread your issue and now understand. I find using three backticks to open and close the code block, then the language name works well, (such as ` ```ruby ` top open and then ` ``` ` to close), to style code rather than the `{% highlight %}` tag. Are you able to give this a go?

**Comment by maedi** [comment]
Thanks the ``` works better as it highlights the code in the text editor too.
