### ISSUE TITLE
Open links in new window

### ISSUE THREAD

**Issue by ureber** [chrisrhymes/bulma-clean-theme#89]
Dear Chris,

thank you for the fantastic theme!

We are looking for a way to open external links in a new window by default (i.e. target="_blank"). This relates especially to links in the callouts and the navigation bar (i.e. links set in the yml files), as html can be used in the md files. We use github-pages and a fork of the bulma-clean-theme as remote theme. We tried the jekyll-target-blank plugin in the _config.yml of both our website and the theme fork, which didn't work. Is there a way to achieve this using the theme?

We very much appreciate your work! Thanks!

**Comment by chrisrhymes** [comment]
Hi @ureber GitHub pages only supports certain plugins so I'm assuming the jekyll-target-blank plugin isn't supported. I'm not sure of a way of doing this automatically.

**Comment by ureber** [comment]
Thank you, @chrisrhymes, for your response. Do you see a way to do this for the links manually? We tried it with a href entry in the markdown files of the page, but were unsuccessful. The theme seems to override this.
