### ISSUE TITLE
Specify custom page for sidebar?  

### ISSUE THREAD

**Issue by 1RedOne** [chrisrhymes/bulma-clean-theme#91]
Hi!  

I've been migrating my blog from WordPress to Jekyll and have fallen in love with this theme.   

The only thing I'm missing now is how to control what the sidebar looks like.  When I turn 'Show_sidebar' to true now, it looks to be using the index page again as its source, as shown in this screenshot.

![image](https://user-images.githubusercontent.com/1247626/108228984-5c2e8c00-710d-11eb-9222-1c082ea20a1e.png)

I want to have the sidebar enabled on all pages on my blog so I have it specified in my `config.yml` file.  

Is there a way I can specify which `.md` file to use for my sidebar?  I'd ideally then just put a few chunks of markdown in it and be done.

### Example Sidebar from WordPress

![image](https://user-images.githubusercontent.com/1247626/108229195-9566fc00-710d-11eb-8588-0d15a5749749.png)

Thank you very much for this awesome theme!

**Comment by chrisrhymes** [comment]
Hi @1RedOne the sidebar content is the `_includes/latest-posts.html` file in the theme. To override this, just create your own `_includes/latest-posts.html` file in your repo and customise it as you see fit. Please see [Overriding Theme Defaults](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) in the Jekyll docs for more information.

**Comment by 1RedOne** [comment]
How would you feel about me doing a PR to the readme to call this out for future folks like me who don't read too good? :)
