### ISSUE TITLE
Default Code Language?

### ISSUE THREAD

**Issue by 1RedOne** [chrisrhymes/bulma-clean-theme#94]
Hi!

  Coming from this issue #86, you pointed out the great tip of using 

```
```language
```

as a good way to do syntax highlighting.  I have a blog that largely uses a certain language (it's like always writing about PowerShell).  I have hundreds of old posts, is there a way to set a default language for syntax highlighting in my config.yml file?  

In my imaginary usage, I'd set 

`syntaxLanguage : powershell`

and not have to specify it for every snippet.

Thanks!

**Comment by chrisrhymes** [comment]
Hi, I have no experience of doing this, but you might be able to configure [Kramdown options](https://jekyllrb.com/docs/configuration/markdown/) to do something. 
It would be better to ask this question on somewhere like [Jekyll talk](https://talk.jekyllrb.com/)
