### ISSUE TITLE
How to use app.scss to modify a value?

### ISSUE THREAD

**Issue by 1RedOne** [chrisrhymes/bulma-clean-theme#99]
Hi!  I want to modify the padding of this class:

```
<div class="hero-body hero-darken">
```

I read the docs but don't understand where or how to overload it here within app.scss.  I want to set 

`.hero.is-medium .hero-body ` padding to the following rem value for padding:

` padding: 7rem 1.5rem;`

**Comment by chrisrhymes** [comment]
You should be able to use the sass variable $hero-body-padding-medium in your app.scss to configure a custom padding value. 

The variables are at the bottom of this page:
https://bulma.io/documentation/layout/hero/
